# Site settings
title: Kirby's Dream Land
header-img: img/home-bg.png
email: jkirbycampbell@gmail.com
copyright_name: kirbycampbell
description: > # this means to ignore newlines until "baseurl:"
  A Day in the Life/ White Ferrari
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kirbycampbell
learn_profile: kirbycampbell
email_username: jkirbycampbell@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
